version: '3.7'
services:
  api:
    build: ./thesis-api
    ports:
        - "5000:5000"
  app:
    build: ./thesis-app
    ports:
        - "80:80"
    depends_on:
      - api
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: