version: '3.7'
services:
  api:
    build: ./api
    ports:
        - "5000:5000"
  app:
    build: ./app
    ports:
        - "4200:80"
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: